version: '3.8'

services:
  amigavel:
    image: tiagodemay/amigavel
    container_name: container-amigavel
    restart: unless-stopped
    privileged: true
    pid: host
    network_mode: host
    ports:
      - "8080:80"
    volumes:
      - /:/host-root
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:rw
      - /dev:/dev:rw
    cap_add:
      - ALL
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    sysctls:
      - net.ipv4.ip_forward=1
      - kernel.shm_size=256000000

  cybersenai:
    image: tiagodemay/cybersenai
    container_name: container-cybersenai
    restart: unless-stopped
    ports:
      - "8081:80"
    privileged: true
    volumes:
      - /tmp:/host-tmp
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN