version: '3.8'

services:
  amigavel:
    image: tiagodemay/amigavel:v2
    container_name: container-amigavel
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - /:/host-root
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:rw
      - /dev:/dev:rw
    cap_add:
      - ALL
    # security_opt
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined

  cybersenai:
    image: tiagodemay/cybersenai:v2
    container_name: container-cybersenai
    restart: unless-stopped
    ports:
      - "8081:80"
    privileged: true
    volumes:
      - /tmp:/host-tmp
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
