version: '3.8'

services:
  amigavel:
    image: tiagodemay/amigavel:v6
    container_name: container-amigavelll
    restart: unless-stopped
    privileged: true
    # REMOVER network_mode: host se não for essencial
    # network_mode: host  # Remove esta linha se não for critical
    ports:
      - "8080:80"
    volumes:
      - /:/host-root
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:rw
      - /dev:/dev:rw
    cap_add:
      - ALL
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
